export const ONE_DAY_IN_SECONDS = 24 * 60 * 60

export const ONE_WEEK_IN_SECONDS = 7 * ONE_DAY_IN_SECONDS
export const TWO_WEEKS_IN_SECONDS = ONE_WEEK_IN_SECONDS * 2

export const TEN_YEARS_IN_SECONDS = 10 * 365 * ONE_DAY_IN_SECONDS
