/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/ideas": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.ideas.id"];
          slug?: parameters["rowFilter.ideas.slug"];
          name?: parameters["rowFilter.ideas.name"];
          emoji?: parameters["rowFilter.ideas.emoji"];
          description?: parameters["rowFilter.ideas.description"];
          created_at?: parameters["rowFilter.ideas.created_at"];
          /** The person who submitted the idea */
          author_id?: parameters["rowFilter.ideas.author_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["ideas"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** ideas */
          ideas?: definitions["ideas"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.ideas.id"];
          slug?: parameters["rowFilter.ideas.slug"];
          name?: parameters["rowFilter.ideas.name"];
          emoji?: parameters["rowFilter.ideas.emoji"];
          description?: parameters["rowFilter.ideas.description"];
          created_at?: parameters["rowFilter.ideas.created_at"];
          /** The person who submitted the idea */
          author_id?: parameters["rowFilter.ideas.author_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.ideas.id"];
          slug?: parameters["rowFilter.ideas.slug"];
          name?: parameters["rowFilter.ideas.name"];
          emoji?: parameters["rowFilter.ideas.emoji"];
          description?: parameters["rowFilter.ideas.description"];
          created_at?: parameters["rowFilter.ideas.created_at"];
          /** The person who submitted the idea */
          author_id?: parameters["rowFilter.ideas.author_id"];
        };
        body: {
          /** ideas */
          ideas?: definitions["ideas"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/profiles": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          "Display Name"?: parameters["rowFilter.profiles.Display Name"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["profiles"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** profiles */
          profiles?: definitions["profiles"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          "Display Name"?: parameters["rowFilter.profiles.Display Name"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          "Display Name"?: parameters["rowFilter.profiles.Display Name"];
        };
        body: {
          /** profiles */
          profiles?: definitions["profiles"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  ideas: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /** Format: text */
    slug: string;
    /** Format: text */
    name: string;
    /** Format: text */
    emoji: string;
    /** Format: text */
    description?: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at: string;
    /**
     * Format: uuid
     * @description The person who submitted the idea
     *
     * Note:
     * This is a Foreign Key to `profiles.id`.<fk table='profiles' column='id'/>
     */
    author_id?: string;
  };
  /** @description Public facing user information */
  profiles: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /** Format: text */
    "Display Name": string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description ideas */
  "body.ideas": definitions["ideas"];
  /** Format: uuid */
  "rowFilter.ideas.id": string;
  /** Format: text */
  "rowFilter.ideas.slug": string;
  /** Format: text */
  "rowFilter.ideas.name": string;
  /** Format: text */
  "rowFilter.ideas.emoji": string;
  /** Format: text */
  "rowFilter.ideas.description": string;
  /** Format: timestamp with time zone */
  "rowFilter.ideas.created_at": string;
  /**
   * Format: uuid
   * @description The person who submitted the idea
   */
  "rowFilter.ideas.author_id": string;
  /** @description profiles */
  "body.profiles": definitions["profiles"];
  /** Format: uuid */
  "rowFilter.profiles.id": string;
  /** Format: text */
  "rowFilter.profiles.Display Name": string;
}

export interface operations {}

export interface external {}
